version: '3.7'

services:
  web:
    build:
      context: ..
      dockerfile: ./docker-for-ci/Dockerfile
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file: ../dj_docker01/.env
    volumes:
      - ../dj_docker01:/usr/src/app
